server:
  port: 9091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tuit_dormitory
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5000MB
      enabled: true
      max-request-size: 5000MB
  data:
    redis:
      port: 6379
      host: localhost
springdoc:
  api-docs:
    path: /api-docs
json:
  web:
    token:
      cookie-name: dormitory-jwt
      refresh-cookie-name: dormitory-jwt-refresh
      secret: thisissecretkeyforfacultyapp
      validation-time: 86400000
      refresh-time: 86400000
